spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: zhangsiyuan
    password: zhangsiyuan
#日志文件配置
#输出到控制台 Console 或者文件 File (大小写不敏感)
#默认的日志级别level.root DEBUG
logging:
  appender: Console
  level:
    root: DEBUG