spring:
  profiles:
    active: dev
  application:
    name: pay_merchant
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # sql语句监控 mysql
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # druid的账号密码
    username: root
    password: root
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    logSlowSql: true
  flyway:
    clean-on-validation-error: false
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/test
    out-of-order: true


server:
  port: 8998


#mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/*/*Mapper.xml
  typeAliasesPackage: com.edc.pay.business.entity,com.edc.plugins.dictionary.entity

#logback配置
logging:
  config: classpath:logback-spring.xml
  pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{10} - %msg%n'

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


